name: "pull_request"

on: pull_request

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.kotlin.dsl.internal.io.timeout=120000 -Dorg.gradle.jvmargs="-Xmx5g -XX:+HeapDumpOnOutOfMemoryError -XX:+UseParallelGC -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8"

concurrency:
  group: pull_request-${{ github.ref }}
  cancel-in-progress: true

jobs:

  check:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Knit and API checks
        run: ./gradlew knitCheck apiCheck --scan

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: 'reports-check'
          path: '**/build/reports/**'

  spotless:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Apply Spotless rules
        run: ./gradlew spotlessApply

      - name: Commit newly formatted files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto-apply Spotless rules
          file_pattern: arrow-libs/**/*.kt

  jvm:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: JVM tests
        run: ./gradlew jvmTest --scan

      - name: Code coverage
        if: "! github.event.pull_request.head.repo.fork "
        run: ./gradlew koverXmlReport

      - name: Add code coverage report
        if: "! github.event.pull_request.head.repo.fork "
        id: kover
        uses: mi-kas/kover-report@v1
        with:
          path: build/reports/kover/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Kover Report
          update-comment: true

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: 'reports-jvmTest'
          path: '**/build/reports/**'
